### ISSUE TITLE
Integration with KP Version Checking?

### ISSUE THREAD

**Issue by photonometric** [Eveldee/KeePass-ExeIconPicker#2]
On the KP update checker window, ExeIconPicker seems to error out:

![image](https://user-images.githubusercontent.com/6432099/81635071-42be1e00-93de-11ea-9ab9-add9bb4b886d.png)

Apparently to "participate" in this feature, plugin authors need to host a simple file with the current version written inside it. Maybe this can be placed in the github repo? The KeePass page on "How-To Develop a 2.x Plugin" has a [detailed section](https://keepass.info/help/v2_dev/plg_index.html#upd) on this function.

While useful and convenient, this obviously isn't a critical issue. It's easy enough to recieve notifications of new releases here in GitHub. But it is a bit disconcerting to see the plugin with no less than 3 error indications whenever anything else pops up that Update notify window. Would be much nicer to see a big green comforting "up to date" check mark next to it! ;)

**Comment by Eveldee** [comment]
I can try to make it even though I don't think there will be a lot of update, thank you for linking all the needed info!

**Comment by Eveldee** [comment]
Implemented in version **[v1.1.0.0](https://github.com/Eveldee/KeePass-ExeIconPicker/releases/tag/v1.1.0.0)**
