### ISSUE TITLE
update

### ISSUE THREAD

**Issue by seddon72** [Eveldee/KeePass-ExeIconPicker#8]
![check](https://user-images.githubusercontent.com/17900026/117853150-fcfd9500-b27f-11eb-9470-dd8be8eb34cc.PNG)
![check3](https://user-images.githubusercontent.com/17900026/117853171-025adf80-b280-11eb-9ea7-ec6a8122cb35.PNG)

1.1.1.0 removed keypass removed and reinstalled still would not update to1.2

**Comment by Eveldee** [comment]
Thanks for the info, I uploaded the updated version but before changing version number so it's still 1.1.1.0 while being 1.2, I'm going to fix this asap

**Comment by Eveldee** [comment]
It's updated, and I also fixed the size of the .plgx, thanks for opening the issue 😄
